### ISSUE TITLE
Crash on launch when this mod is enabled.

### ISSUE THREAD

**Issue by iyloMC** [embeddedt/CreateChunkloading#11]
A lot of other fabric mods seem to cause a launch-crash when this mod is enabled. This issue is not present when this mod is disabled, even with Create enabled.
See crash report here: https://pastebin.com/sJEBQpJs

The crash report says that MainMenuCredits is the reason for the crash, but when I turn that mod off, a different one throws the same error, on and on down the list. The only solution seems to be to disable Create ChunkLoading

**Comment by embeddedt** [comment]
I'm not sure what would cause this. Do you have the full game log, by chance?

**Comment by embeddedt** [comment]
I'm closing this as there are too many mods in the crash report to recreate the situation myself and no additional information has been provided. If someone can reproduce this, please open a new issue.
