### ISSUE TITLE
Fabric version is for Create 0.5, but Create Fabric 0.5 is still in development

### ISSUE THREAD

**Issue by xorblo-doitus** [embeddedt/CreateChunkloading#14]
The only Fabric version of [Create Chunkloading on CurseForge](https://www.curseforge.com/minecraft/mc-mods/create-chunkloading/files) is for Create 0.5, but 0.5 is not out for [Fabric port of Create](https://www.curseforge.com/minecraft/mc-mods/create-fabric)

**Comment by embeddedt** [comment]
There are previous Fabric versions if you scroll down on your first link. https://www.curseforge.com/minecraft/mc-mods/create-chunkloading/files/3739771 is for Create 0.4.

**Comment by xorblo-doitus** [comment]
Thank you very much, i already scrolled, but i didn't see the "View all" button, and thought that the bottom table was already displaying all files.
