### ISSUE TITLE
Mod not working

### ISSUE THREAD

**Issue by BEMZ01** [embeddedt/CreateChunkloading#15]
Hi there!

On a server i play with some friends and we built one of the chunk loader blocks to sit at the bottom of a mob farm. We don't believe it is working, does it have to be part of a moving contraption?

Minecraft V: 1.18.2
Create V: 0.5.0.E
Create Chunk loading V: 1.2.1-forge

**Comment by embeddedt** [comment]
Yes, it only works if the contraption is an entity (e.g. a minecart contraption that is an entity, but not moving will work). I think this is mentioned on the mod page but I could be mistaken.

**Comment by BEMZ01** [comment]
So if I placed the block on a mechanical bearing and made it spin it would keep the chunk loaded?

**Comment by embeddedt** [comment]
Powering a cart assembler with the chunkloader on top should be enough. The contraption doesn't need to move; it just needs to be an entity.
