### ISSUE TITLE
[Feature Request] Random Tick Loader

### ISSUE THREAD

**Issue by gittibene** [embeddedt/CreateChunkloading#25]
Would it be possible to add a second chunk loader that supports random ticking/ mob spawning?

**Comment by embeddedt** [comment]
Thanks for opening the feature request, however I think this is something I will not pursue within this mod as I only really wish to support the basic use case of keeping a contraption moving through unloaded chunks (e.g. for a mining bore).

**Comment by gittibene** [comment]
I see, please consider updating your mod description with a warning about random ticking then. Was quite disappointed to notice this after building a gigantic automated crop farm with your chunk loaders..

**Comment by embeddedt** [comment]
Which modloader are you using?

**Comment by gittibene** [comment]
Fabric 1.19.2. The fact that there`s no redstone toggable chunk loader for this version with random ticking adds to my frustration :D

**Comment by embeddedt** [comment]
The issue is that vanilla imposes a restriction that no matter what mechanism you use to load a chunk it only receives random ticks if a player is within 128 blocks of its center. Fixing that is rather invasive which is why I don't really want to do it in a basic Create addon. That's also probably why you don't see many mods that offer the feature.

**Comment by gittibene** [comment]
Yeah, it sucks. Looking at the insane amount of issues that chunkloaders have that DO random ticks i totally see where you're coming from. Just reeaally annoying from a gameplay perspective especially because stuff that needs random ticks usually takes so much time.

**Comment by embeddedt** [comment]
One option which might be a fun project would be to look into Carpet's fake players, I believe they behave like actual player entities so you could possibly put one in a minecart, and make a redstone contraption that moves them into the farm when you want it loaded. This would of course impose some additional lag as compared to having a chunk loader that did random ticks by itself, but it could work in theory.

**Comment by gittibene** [comment]
Thanks for trying to find a solution, sadly carpet is a no-go for me because i don't feel like typing console commands is an acceptable gameplay mechanic. Really love your approach with contraption-based loaders that work with no UI/commands whatsoever.
