### ISSUE TITLE
Still crashes with create 0.5.1 

### ISSUE THREAD

**Issue by Fade-Alchemist** [embeddedt/CreateChunkloading#28]
Per issue #26  Create has been updated and patched, but the crash persists. 

Launching crashes with error:
Unmet dependency listing:
	 - Mod 'Create Chunkloading' (createchunkloading) 1.4.0 requires version 0.5.1 or later of mod 'Create' (create), but only the wrong version is present: 0.5.1-b-build.1078+mc1.18.2!
	 
	 The complete log is attached.

[latest.log](https://github.com/embeddedt/CreateChunkloading/files/11927181/latest.log)

**Comment by embeddedt** [comment]
Fixed in 1.4.1.
