### ISSUE TITLE
1.18 chunkloading issue

### ISSUE THREAD

**Issue by MuradAkh** [embeddedt/CreateChunkloading#5]
Hey I saw on curseforge that you had an issue with chunkloading in 1.18. 

I also ran into an issue when portion little logistics to 1.18. It was resolved by setting the ticking parameter to false when you call forge chunk manager. My entities still tick from what I've tried. You might want to double check if other stuff ticks.

For reference 
https://github.com/MuradAkh/LittleLogistics/pull/96/files

**Comment by embeddedt** [comment]
Thank you so much for this information! That's a very counterintuitive fix,
but if it works, I'll be more than happy to give you credit.

By the way, I've seen your mod before - very cool concept.

**Comment by embeddedt** [comment]
It [worked perfectly](https://www.curseforge.com/minecraft/mc-mods/create-chunkloading/files/3662020)! Thanks again for your help.

**Comment by MuradAkh** [comment]
Yeah I'm not entirely sure if this is a forge bug or ticking is meant for something else. I will probably look more deeply into it when I have time. Did you verify that tile entities still tick?

**Comment by embeddedt** [comment]
I suspect it's a Forge bug, because this worked correctly in 1.16 (at least for me), and the API contract didn't change. I didn't check on tile entities because Create contraptions are real entities. I would assume that real entities and tile entities behave the same way, but I could be wrong.

**Comment by embeddedt** [comment]
Looks like https://github.com/MinecraftForge/MinecraftForge/pull/8775 will solve this for 1.19 and a backport for 1.18 is also open.
