### ISSUE TITLE
Not working with the newest create update

### ISSUE THREAD

**Issue by KantarowskiMichal** [embeddedt/CreateChunkloading#7]
the mod does not load properly with the 0.5.0b create update ( I was using forge )

**Comment by MinoCraft** [comment]
o/

Here, you can found crash report about this issue:

https://www.dropbox.com/s/4nq4jn7acj27fbt/crash-2022-07-12_15.52.05-fml.txt?dl=0

Thanks in advance

**Comment by ZEROX7** [comment]
SAME 
[crash-2022-07-12_15.58.15-fml.txt](https://github.com/embeddedt/CreateChunkloading/files/9093651/crash-2022-07-12_15.58.15-fml.txt)

**Comment by embeddedt** [comment]
I am working on an update; it will be out today most likely.

**Comment by embeddedt** [comment]
Thank you for the reports; 1.2.0 now supports Create 0.5. It will not work on older Create versions.
