### ISSUE TITLE
Bricked world

### ISSUE THREAD

**Issue by NoRestWhenWicked** [embeddedt/CreateChunkloading#9]
Modlist-

Create
Flywheel
Alex's Mobs
Ecologics
Exotic Birds
Optifine

Issue-

I put a chunk loader on a powered create clock module (the clock mechanism with sticky rotational front) on the minutes hand for continual uploading. 

After first log out, the world is bricked and will not load.

The chunk loader is in continuous entity form, as part of the clock module. I'm fairly sure this broke the world.

Was survival playthrough with many hours, please 2 fix <3

Additional info-

No other modded blocks used, oak planks for hour hand, nether brick wall for minute hand, chunk loader attached to wall with glue at top of wall.

Tried uninstalling chunk loader mod, world is still bricked.

**Comment by embeddedt** [comment]
Do you have a log from when this happened? Is it reproducible if you try it in a new world?

**Comment by embeddedt** [comment]
I'm closing this as it's not actionable in its current state. If you are able to provide more information, let me know and I'll reopen the issue.
